php:
    frontend:
        name: apache-mod-php
        options:
            vhost_file: conf/apache-vhost.conf
            modules:
                - rewrite

hooks:
    build:
        - wget --quiet http://getcomposer.org/composer.phar -O composer.phar && chmod +x composer.phar
        - ./composer.phar install